= Event Driven
:jbake-date: 2020-01-20


== What is event-driven software
Event-driven software is a paradigm in which the flow of the application is determined by events such as user actions, sensor outputs, or message passing from other programs. In the case of algo-trading, these actions are often price actions that happen in the market or other financial news.

== Why an event-driven approach?
Event-driven algo-trading platforms provide several advantages over a vectorised approach:

* Reuse - roboquant uses the same event-driven approach for all xref:four_stages.adoc[4 stages] of developing trading strategies, ensuring minimal friction when moving from one stage to the next.

* Avoid Lookahead - With an event-driven test, it is unlikely that the strategy will actually peep into the future since at the time of making any decision in the code, the future data is not yet available.

* Robustness - Live trading is by definition event-driven. So by using the same approach during back testing, it ensures you got have to address use-cases that otherwise wouldn't show up until it is too late.

Although event-driven systems come with the above benefits, they traditionally suffer from two disadvantages over simpler vectorised systems:

. They are more complex to implement and test. That is why using platform like roboquant makes a lot of sense, since then much of the heavy lifting is done by the platform.

. They can be slower to execute compared to a vectorised system. But by using Kotlin and a highly optimized code-base, roboquant is actually faster than most other algo-trading solutions.

To find out more about Events and Actions, check out the documentation on xref:../feed/index.adoc[feeds].