= Features
:jbake-type: doc
:icons: font
:jbake-date: 2020-01-15

This page list the main features of roboquant for each key area: Fast, Flexible, Easy, and Free.
It also provides a short overview of how roboquant compares to some other popular algo-trading software.

== Fast
Nowadays, there is so much more data available than ever before. It would be a lost opportunity not being able to leverage this data to make smarter and better performing strategies. Roboquant can work seamlessly with these large data-sets:

* [x] Fully utilize modern hardware, like large multicore machines
* [x] Highly tuned back-test engine so the engine itself will not become a bottleneck
* [x] Just a few lines of code to run multiple back-test in parallel
* [x] Very fast CSV parsing, allowing to process directories full of CSV files in just seconds
* [x] Support for file formats like Apache Avro™ to further reduce parsing overhead and easily share data sets
* [x] Support for lazy loading of data, so memory doesn't become a constraint
* [x] Several very fast trading algorithms out of the box

== Flexible
Flexible means being able to trade at different markets at different parts in the world. This implies:

* [x] Support for trading assets in different currencies at the same time.
* [x] Roboquant comes out of the box with ready to use currency converters
* [x] Correctly handles data from different time-zones
* [x] Trade traditional asset classes like stocks, options, futures and forex as well as cryptocurrencies
* [x] Support for simple trading strategies and advanced machine learning based approaches
* [x] Support for simple and complex order types

Flexible also means roboquant is fully modular and can be extended:

* [x] Integrate with 3rd party brokers and exchanges
* [x] Add new type of data feeds ranging from price feeds and fundamental data to unstructured data like images
* [x] Support for custom order types

== Easy
Developing trading algorithms requires a lot of different skills. You need to know of course a lot about trading itself, but also programming and even a bit of statistics comes in handy. Roboquant tries to cater for both experienced and less experienced user.

=== Interactive Development
Roboquant can be run inside a Jupyter Notebook which provides a very easy entry for people who might find a full-blown development environment too much hassle.A lot of effort went into designing an API that is very easy to use from a
Notebook.

* [x] Graceful introduction of complexity.In other words: simple things should be simple, complex things should be possible
* [x] Many convenience methods to get results with minimal amount of coding
* [x] Many charts out of the box that provides insights into the feeds and the results of a run
* [x] Sensible defaults for many arguments, so you don't have to specify them all the time

Once you code base grow too large for a notebook, the exact same code can be used in a traditional IDE.

[#_order_management]
=== Order management
One of the hardest (and most overlooked aspect) of algorithmic trading is order management, especially when your goal is to bring it to a live trading environment.There are so many things that potentially can go wrong and will cost you real money.It is a real endeavor to translate signals into actual orders and manage these outstanding orders.

Because of this, roboquant separates the generation of signals (Strategy) from the actual orders (Policy).This allows algo-traders to focus on the generation of signals and pick the order management that fits the risk profile and trading style.And if full control over portfolio- and order-management is required, it is still available.

=== Batteries included
* [x] Over 200 technical indicators that are very easy to use in your own strategies
* [x] Powerful charts when running back-tests in a Jupyter Notebook
* [x] Support for many back-testing approaches, like for example walk-forwards.
* [x] Pluggable metrics you can use to see how a strategy is performing
* [x] An advanced simulated broker for back-testing and live-testing that can handle both basic and advanced order types
* [x] Integration with 3rd party brokers and data providers

== Free
In order to build the greatest environment for algo-trading possible, it is important to make sure this environment is free for anyone to use, contribute and improve on. That is why roboquant is developed under the permissive Apache 2.0 license and welcomes people to contribute.

But it doesn't stop at the software. For real progress also data has to become freely available so performance of various strategies can be more easily compared. For inspiration look at what quality training data did for deep learning networks and the progress in recent years.

== Feature Comparison
The following table provide a quick overview of how the features of roboquant stack up to some alternative algo-trading frameworks. Of course, we are not completely objective, so we recommend trying them out yourself and see which one suits you best.

[frame=ends]
[.table]
[cols="<,^,^,^,^"]
|===
|Feature |roboquant |Backtrader | Zipline| Lean (QuantConnect)

|Back Testing|&check;| &check;|  &check;| &check;
|Live Testing|&check;| &check;|  &cross;| &check;
|Paper Trading|&check;| &check;| &cross;| &check;
|Live Trading| &check;| &check;| &cross;| &check;
|Primary Language| Kotlin| Python| Python| C#
|License| Apache| GPL| Apache| Apache
|Active Development|&check;| &check;| &cross;| &check;
|Multi Currency| &check;|  &cross;| &cross;| &cross;
|Crypto Exchanges| &check;|  &check;| &cross;| &check;
|Complex Order Types| &check;| &check;| &cross;| &cross;
|Multi Region| &check;|  &cross;| &cross;|&check;
|Performance| high| low| mid| high
|Code base| small| midsize| large| very large
|Jupyter Notebook| &check;|  &check;| &check;| &cross;
|===
