= Time
:source-highlighter: rouge
:sourcefile: ../../../samples/currencies.kt
:jbake-date: 2020-01-31
:icons: font

Roboquant is build from the ground up to support trading in assets that have different currencies. So for example at the same time you can hold US stocks and EuroNext stocks in your portfolio and trade them.

In order to make it easier to trade in a multi-regions, roboquant introduces a number of domain classes: <<Timeline>>, <<Timeframe>>, <<ZonedPeriod>>.

Internally all time in stored in `Instant` type and so can always be easily compared, regardeless from which timezone the information originated from. The `Event` for example exposes its time attribute as an `Instant`.

== Timeline
Timeline is just a list of `Instant` instances in chronological order. For example a historical feed has a timeline, which represents all the moments in time that the feed has data available. A timeline has zero or more elements, but is always finite.

== Timeframe
`Timeframe` represents a period of time with a start-time (inclusive) and an end-time (exclusive).

It is used throughout roboquant, but one particular use-case is that you can restrict a `run` to a particular timeframe. So instead of one large run over all the events in a `Feed`, you can have multiple smaller runs. The `Timeframe` has several helper methods that makes it easier to split a timeframe into smaller parts.

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=amount]
----

== ZonedPeriod
When dealing with time duration, there are actual two types of duration in Java/Kotlin:

1. `Period` which you use for days and longer and is timezone sensitive
2. `Duration` which you use for days and shorted and is not timezone sensitive

The ZonedPeriod in roboquant makes this a single implementation.

