= Domain Model
:source-highlighter: rouge
:sourcefile: ../../samples/currencies.kt
:jbake-date: 2020-03-01
:icons: font


Besides components like Strategy and Policy, roboquant also comes with a number of domain specific classes that make it easier to implement robust trading strategies.


== Money
In order to make it easier to develop in a multi-currency setup, roboquant introduces a number of domain classes: <<Currency>>, <<Amount>>, <<Wallet>> and <<ExchangeRates>> that will help.

=== Currency
The roboquant `Currency` class represents any type of currency. It follows closely the interface that comes with the standard  Java Currency class, but is independent of it. The main reason is that the Java implementation doesn't support cryptocurrencies while the roboquant implementation supports any type of currency.

Also several common currencies are predefined, to make it easier to work with.

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=currency]
----

=== Amount
An amount can hold the value for a single currency. You can create a new `Amount` using the constructor. But you can also use the extension functions that are defined commonly used currencies (f.e. 120.EUR). Amounts are just like numbers immutable.

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=amount]
----

NOTE: Amounts store their values internally as Doubles and not BigDecimals. For (simulated) trading the potential loss of precision is not an issue and the benefits are much better performance and lower memory consumption.

=== Wallet
A `Wallet` can hold amounts of multiple currencies at the same time. You can create a new `Wallet` by using its constructor, or by adding multiple amounts together. You can also deposit and withdraw amounts in a wallet. A `Wallet` instance is mutable.

There is an important difference between `deposit` method and using the `+ operator`. The `deposit` method will modify the existing instance while the `+ operator` will return a new wallet instance.

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=wallet]
----

NOTE: If you add two amounts together you'll always get a new `Wallet` instance back, even if the two amounts have the same currency.

=== ExchangeRates
`ExchangeRates` is an interface that supports the conversion of an amount from one currency to another one. Although you can invoke the API of an implementation directly, typically you would use the `convert` method of an `Amount` or `Wallet` instance.

The `Config.exchangeRates` property is used by the components to perform the actual conversion. So you can change this property and all code from now on will use this new implementation.

The `ExchangeRates` interface also supports different rates at different moments in time, but it depends on the actual implementation if the provided time parameter is taken into consideration. One of the implementations that comes out of the box with roboquant, is the `ECBExchangeRates` which contains daily exchange rates for most fiat currencies from the year 2000 onwards.


[source,kotlin,indent=0]
----
include::{sourcefile}[tag=er]
----


== Time
In order to make it easier to trade in a multi-regions, roboquant introduces a number of domain classes: <<Timeline>>, <<Timeframe>>, <<ZonedPeriod>>.

Internally all time in stored in `Instant` type and so can always be easily compared, regardless from which timezone the information originated from. The `Event` for example exposes its time attribute as an `Instant`.

=== Timeline
Timeline is just a list of `Instant` instances in chronological order. For example a historical feed has a timeline, which represents all the moments in time that the feed has data available. A timeline has zero or more elements, but is always finite.

=== Timeframe
`Timeframe` represents a period of time with a start-time (inclusive) and an end-time (exclusive).

It is used throughout roboquant, but one particular use-case is that you can restrict a `run` to a particular timeframe. So instead of one large run over all the events in a `Feed`, you can have multiple smaller runs. The `Timeframe` has several helper methods that makes it easier to split a timeframe into smaller parts.

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=amount]
----

=== ZonedPeriod
When dealing with time duration, there are actual two types of duration in Java/Kotlin:

1. `Period` which you use for days and longer and is timezone sensitive
2. `Duration` which you use for days and shorted and is not timezone sensitive

The ZonedPeriod in roboquant makes this a single implementation.

