= Domain Model
:source-highlighter: rouge
:sourcefile: ../../samples/domainmodel.kt
:jbake-date: 2020-03-01
:icons: font

== Approach
Besides core components like `Strategy` and `Policy`, _roboquant_ also comes with a number of domain specific classes that make it easier to implement robust trading strategies. The two main focus areas are:

1. <<Monetary>> related functionality
2. <<Time>> related functionality

This approach makes it very easy to deal with these entities without much code. This is also where many of the Kotlin language features come in handy like the support for operator overloading and extension functions.

== Monetary
In order to make it easier to develop solutions in a multi-currency setup, _roboquant_ introduces a number of money-related domain classes: <<Currency>>, <<Amount>>, <<Wallet>> and <<ExchangeRates>>.

=== Currency
The _roboquant_ `Currency` class represents any type of currency. It follows closely the interface tof the standard Java Currency class, but is independent of it. The main reason is that the Java implementation doesn't support cryptocurrencies while the _roboquant_ implementation supports any type of currency. Several common currencies are predefined, to make it easier to work with and avoid typing mistakes.

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=currency]
----

=== Amount
An amount can hold the value for a single currency. You can create a new `Amount` using the constructor. But you can also use the extension functions that are defined for commonly used currencies (e.g. 120.EUR). Amounts, just like numbers, are immutable.

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=amount]
----

NOTE: Amounts store their values internally as a `Double` and not a `BigDecimal`. For (simulated) trading the potential loss of precision is not an issue and the benefits are improved performance and lower memory consumption.

=== Wallet
A `Wallet` can hold amounts of multiple currencies at the same time. You can create a new `Wallet` by using its constructor, or by adding multiple amounts together. You can also deposit and withdraw amounts in a wallet. A `Wallet` instance is mutable.

There is an important difference between `deposit` method and using the `+ operator`. The `deposit` method will modify the existing instance while the `+ operator` will return a new wallet instance.

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=wallet]
----

NOTE: If you add two amounts together you'll always get a new `Wallet` instance back, even if the two amounts have the same currency.

=== ExchangeRates
`ExchangeRates` is an interface that supports the conversion of an amount from one currency to another one. Although you can invoke the API of an implementation directly, typically you would use the `convert` method of an `Amount` or `Wallet` instance.

The `Config.exchangeRates` property is used by the components to perform the actual conversion during a run. So you can change this property and all code from now on will use this new implementation. The default is that no conversion will be performed and an exception will be thrown if a conversion is required. As long as you trade in a single currency (like USD), this default will be sufficient.

The `ExchangeRates` interface also supports different rates at different moments in time, but it depends on the actual implementation if the provided time parameter is taken into consideration. One of the implementations that comes out of the box with _roboquant_ is the `ECBExchangeRates`, which contains daily exchange rates for most fiat currencies from the year 2000 onwards.


[source,kotlin,indent=0]
----
include::{sourcefile}[tag=er]
----


== Time
In order to make it easier to trade in multiple regions, _roboquant_ introduces a number of time related domain classes: <<Timeline>>, <<Timeframe>>, <<TradingPeriod>>.

Internally all time in stored as an `Instant` type and so can always be easily compared, regardless of from which timezone the information originated. `Event`, for example, exposes its time attribute as an `Instant`.

=== Timeline
Timeline is a list of `Instant` instances ordered in chronological order. For example, a CSVFeed has a timeline, that represents all the moments in time for which the feed has data available. A timeline has zero or more elements, but is always finite.

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=timeline]
----

=== Timeframe
`Timeframe` represents a period of time with a start-time (always inclusive) and an end-time (inclusive or exclusive).

It is used throughout _roboquant_, but one particular use case is that you can restrict a `run` to a particular timeframe. So instead of one large run over all the events in a `Feed`, you can have multiple smaller runs. The `Timeframe` has several helper methods that make it easier to split a timeframe into smaller parts.

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=tf]
----

There is also a set of predefined timeframes for significant periods in the history of trading. This comes in handy if you want to validate the performance of your strategy in a certain type of regime.

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=predefined]
----

=== TradingPeriod
When dealing with time duration, there are actual two types of duration in Java/Kotlin world:

1. `Period` which you use for days and longer and is timezone dependent
2. `Duration` which you use for hours and shorter and is timezone independent

The `TradingPeriod` class in _roboquant_ unifies this into a single implementation and make it easy to use them in combination with `Timeframe`, `Instant` and `ZonedDateTime` instances. You can do things like:

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=tradingperiod]
----

NOTE: whenever a timezone is required for an operation and none is supplied, `UTC` will be used. This provides consistent behavior across machines in different timezones.

=== Exchanges and TradingCalendars
An asset is linked to a single exchange and that exchange has a time-zone associated with it. This is mostly relevant during back-testing when certain time-in-force policies need to be evaluated (like good for today).

The exchange also has a `TradingCalendar` associated with it, that determines what are the valid trading hours for that particular exchange.

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=assets]
----

== Size
Order sizes and position sizes are expressed as an instance of the `Size` class. For the internal working of _roboquant_ there is no differentiation between fractional and non-fractional orders. All are expressed using the same `Size` class.

This class is precise till 8 decimal digits and ensures that there are no rounding errors when for example closing a position. It is an immutable class, but you can perform simple arithmetic on it.

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=size]
----