= Integration
:jbake-date: 2020-01-01
:icons: font
:source-highlighter: rouge
:dotenvfile: ../../samples/dotenv
:sourcefile: ../../samples/integration.kt

There are several types of integrations available with 3rd parties:

* Historic data feeds
* Live data feeds
* Brokers implementations
* Exchange rates

In some cases a single 3rd party provides all types of functionality, or sometimes they are just specialised for a subset. You can combine several of these 3rd parties together in a single run, for example using a data feed from one provider and the broker functionality from another one.

One of the design principles is that _roboquant_ tries to avoid exposing 3rd party APIs directly and typically wraps them in _roboquant_ equivalent types. This makes it easier to switch between different providers and also reduces the learning curve.

== Modules & Packages
The third party integrations have their own modules and are not part of the core `roboquant` module:

* roboquant-extra for the "traditional" broker and data feed providers
* roboquant-crypto for cryptocurrency related 3rd parties
* roboquant-ibkr for Interactive Brokers

Include these modules in your Maven or Gradle build. Except for `roboquant-ibkr`, these modules are included by default in the Jupyter Notebooks.

In order to use the 3rd party integration, you'll first have to import the package. All third party integration have their own package directly under `org.roboquant`. So you can import all the required classes for OANDA as follows:

[source, kotlin]
----
import org.roboquant.oanda.*
----

== Configuration
When you want to integrate with a 3rd party, you most likely require credentials to gain access to their APIs. Often this is in the form of an API key and/or secret. You can include these credentials directly in your source code, however _roboquant_ offers better and more secure alternatives.

The following list shows the steps _roboquant_ uses to resolve these configuration parameters:

. If the credentials are provided directly in the code when calling the API, use these, otherwise go to next step.
. If the credentials are provided as startup parameter to the JVM with the -D syntax, use these, otherwise go to next step.
. If the credentials are set as system environment variable (export MY_KEY="some value"), use these, otherwise go to next step.
. If the credentials are set in a property file called ".env" in the working directory, use these, otherwise go to next step.
. If the credentials are set in a property file called "dotenv" in the working directory, use these, otherwise go to next step.
. If the credentials are set in a property file called ".env" in the $HOME/.roboquant directory, use these, otherwise not found.

The following provides an overview of the used properties in _roboquant_

[source, properties, indent=0]
----
include::{dotenvfile}[]
----

== Supported 3rd parties
The following table shows which 3rd parties are supported out of the box and what functionality the integration offers:

[cols="<,^,^,^,^"]
|===
|3rd party |Historic feed |Live feed |Broker |Exchange rates

|Interactive Brokers|✓|✓|✓|✓
|Alpaca|✓|✓|✓|
|OANDA|✓|✓|✓|✓
|Polygon.io|✓|✓||
|Yahoo Finance|✓|||
|Alpha Vantage|✓|||
|Binance|✓|✓|✓|
|XChange (60+ crypto exchanges)|✓|✓|✓|
|ECB||||✓
|===

NOTE: _roboquant_ is open source software that is developed independently of these 3rd party companies. There are no direct or indirect ties to any of these companies.

=== Yahoo
You can use the `YahooHistoricFeed` to retrieve historic prices from Yahoo Finance. This is one of the few APIs out there that you can use without requiring a registration or an API key.
[source, kotlin,indent=0]
----
include::{sourcefile}[tag=yahoo]
----

=== Alpaca
The integration with Alpaca covers their broker API as well as their historic and live market data APIs. In order to use this, you'll need at least register and get a paper-trading account with an API-key.

[source, kotlin,indent=0]
----
include::{sourcefile}[tag=alpacahistoric]
----

[source, kotlin,indent=0]
----
include::{sourcefile}[tag=alpacalive]
----

[source, kotlin,indent=0]
----
include::{sourcefile}[tag=alpacabroker]
----

=== OANDA
The integration with OANDA covers their broker API as well as their historic and live market data. In order to use this, you'll need at least register and get a paper-trading account with an API-key.

[source, kotlin,indent=0]
----
include::{sourcefile}[tag=oandahistoric]
----

[source, kotlin,indent=0]
----
include::{sourcefile}[tag=oandalive]
----

[source, kotlin,indent=0]
----
include::{sourcefile}[tag=oandabroker]
----

== Polygon
Polygon has several type of subscriptions available, depending on your needs. The free version only provides access to historic data, while the paid versions also provide live data.

[source, kotlin,indent=0]
----
include::{sourcefile}[tag=polygonhistoric]
----

[source, kotlin,indent=0]
----
include::{sourcefile}[tag=polygonlive]
----

== ECB
The ECB (European Central Bank) publishes since the start of the Euro the daily historic exchange rates with almost all other fiat currencies in the world. Roboquant can automatically download these exchange rates from their website and use them for currency conversions during trading.

[source, kotlin,indent=0]
----
include::{sourcefile}[tag=ecb]
----


== Alpha Vantage
Alpha Vantage provides a rich set of historic stock prices, not only those stocks listed on US exchanges.

[source, kotlin,indent=0]
----
include::{sourcefile}[tag=alphahistoric]
----


== Adding new 3rd party integrations
Adding integration with a 3rd party is not difficult. Integration with 3rd party data providers is straight forward and requires implementing a single interface. Depending on the client library that is available, this could take as little as a few hours to a few days. You can read more about the Feed interface that you need to implement right xref:feed.adoc#_custom_feeds[here].

Integrating with a new broker is not hard either, but requires more effort. The most amount of work will be the translation of object exposed by the broker to those used by _roboquant_. For example an Order in _roboquant_ is slightly different from an Order expected by the client library of the broker, and a conversion needs to happen.

For both custom Feed and Broker integrations, it is recommended to first look at some existing integrations and use them as a starting point. And if you have questions, you can always reach out via one of the channels mentioned on the xref:../community.adoc[community page].
