= Metrics
:icons: font
:source-highlighter: rouge
:sourcefile: ../../samples/metrics.kt
:jbake-date: 2020-07-01

Metrics allow you to monitor the progress of a `run` and get the necessary insights how a strategy is performing. Metrics are not limited to back testing and can also be used both during live testing and paper trading.

The configured metrics are invoked at each step in a run. A single metric can return multiple values, each value having it own a unique name. Metrics only calculate the values, the storing and/or logging of these values is done by a `MetricsLogger`.

== Standard Metrics
There are several common metrics included with _roboquant_ that can be easily added to your `Roboquant` instance:

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=standard]
----

TIP: if a metric is very compute intensive, and you don't require it at each step, you can wrap it in a `MetricsScheduler` and configure when it should be invoked.

== Custom Metrics
You can develop your own metrics. The easiest way to do so is to extend the SimpleMetric class. All you have to do is implement that `calc` method and return `MetricResults`, which is just a `typealias` for `Map<String,Number>`

In the `calc` function you have access to both the account object and the event. Metrics also implement the `Component` interface, so can keep state in a metric if required and clean it when a Component lifecycle method is invoked.

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=simple]
----


== Metrics Loggers
A metrics loggers receives the calculated metric values at each step and then stores and/or logs these values. They all implement the `MetricsLogger` interface.

The following metric loggers come out of the box:

- `MemoryLogger`: this is the default logger used if no other logger is configured. It stores all the recorded values in memory and
allows them to be queried afterwards. It also comes with a progress-bar that shows how much time is remaining during
a run.
+
This logger is very useful if you are testing your approach in a Jupyter Notebook or another interactive development
environment.
+
[source,kotlin,indent=0]
----
include::{sourcefile}[tag=standard]
----

- `SilentLogger`: this logger just silently ignores all calculated metric values and is mostly useful for unit tests

- `InfoLogger`: logs metrics using the built-in logger at INFO level.

- `ConsoleLogger`: logs the metrics to the console using a simple `println` statement.

=== Custom Loggers
You can also implement your own metrics logger, for example if you want to store values into a database or have a custom file format that you want to use. The following example shows a minimal example:

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=customLogger]
----