= Policy
:source-highlighter: rouge
:icons: font
:sourcefile: ../../samples/policy.kt
:jbake-date: 2020-05-01

== What is a policy
A `Policy` is responsible for creating the orders that will be placed at the broker. The most common use-case is that a `Policy` does this based on the signals it receives from a `Strategy`, but there are other use-cases.

A good `Policy` implementation is key in making your solution as robust as possible. Important things to consider when implementing a policy:

* What is a good allocation strategy, so how much of your buying power do you allocate to a certain asset
* What order types to create
* How to handle new orders when there are still open orders (for the same asset)
* How to limit the maximum number of orders send to a broker (circuit breaker)
* How to deal with conflicting signals from strategies
* How to handle yo-yo signals (buy-sell-buy-sell) in a short timeframe
* How to manage overall risk and exposure when volatility changes
* How to ensure there is still enough buying power left to avoid margin calls

****
CAUTION: If there is one thing that prevents many from going live with a strategy, it is that there is not a robust policy in place that handles all the possible edge-cases. The logic required in a robust policy is anything but trivial and should incorporate an extensive testing period.
****

== Out-of-the-box policies

=== DefaultPolicy
As the name already suggests, this is the default policy that will be used if no other policy is specified when create an instance of the `Roboquant` class. It provides several configuration properties that influence its behavior.

You can also easily extend the DefaultPolicy to create your own order types.

[source, kotlin]
----
include::{sourcefile}[tag=default]
----


== Fractional Order sizes
Roboquant doesn't make assumptions on the permitted order- and position-sizes. They are not limited to integers only and so there is no restriction on using a broker that supports fractional trading. Since it is the Policy that create the orders, here you can also put any type of order size logic yuo require.

To make it even easier, there is an OrderSizer interface with default implementations you can reuse.


== Custom Policies
In case the out-of-the-box policies will not do, you can implement your own `Policy`. You only have to implement a single method named `act`. This method has access both to the generated signals as well ass the `Account` and `Event`.

[source, kotlin]
----
include::{sourcefile}[tag=basic]
----

So a very naive and not robust implementation could look something like this:

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=naive]
----

Or using the more concise Kotlin way of doing things:
[source,kotlin,indent=0]
----
include::{sourcefile}[tag=naive2]
----


The following example is more realistic and shows an implementation that calculates the ATR (Average True Range) that is than used to set the limit amount in a Limit Order. This example use the `DefaultPolicy` as its base class that will take care of much of the logic like sizing and dealing with concurrent orders.
[source, kotlin,indent=0]
----
include::{sourcefile}[tag=custom3]
----

When developing custom policies, they should not only be robust and deal with corner-cases, but they should also be explainable. Back-testing over large amounts of data is already challenging enough without having a `Policy` in place which behavior is very difficult to wrap your head around. So the KISS design principle (Keep It Simple, Stupid) applies to policies.

== Advanced Policies
Most commonly a `Policy` is used to transform signals it receives from the `Strategy` into orders. But there are other use-cases where the policy is not using Signals to create orders. Common use-case are:

. Re-balancing your portfolio at regular intervals (like monthly) based on some risk profile. Since a `Strategy` doesn't have access to an `Account` and there for also not to a `Portfolio`, this need to be done in a `Policy`.
. Advanced machine learning techniques like reinforcement learning that train the algorithm to directly create orders based on events (and not create intermediate signals).

In these cases you don't require a `Strategy` and implement all the logic in the `Policy` instead. You can use the `NoSignalStrategy` as strategy that doesn't perform any action.

[source, kotlin,indent=0]
----
include::{sourcefile}[tag=advanced]
----

