= Policy
:source-highlighter: rouge
:icons: font
:sourcefile: ../../samples/policy.kt
:jbake-date: 2020-05-01

== What is a policy
The `Policy` is responsible for creating the orders that will be placed at the broker. The most common use case is that a `Policy` does this based on the signals it receives from a `Strategy` (but there are other use cases).

A good `Policy` implementation is key in making your solution as robust as possible. Important things to consider when implementing a policy:

* What is a good allocation strategy, so how much of your buying power do you allocate to a certain asset
* What order types to create
* How to handle new orders when there are still open orders (for the same asset)
* How to limit the maximum number of orders sent to a broker (circuit breaker)
* How to deal with conflicting signals from strategies
* How to handle yo-yo signals (buy-sell-buy-sell) in a short timeframe
* How to manage overall risk and exposure when volatility changes
* How to ensure there is still enough buying power left to avoid margin calls

****
CAUTION: If there is one thing that prevents algo-traders from going live, it is that there is not a robust policy in place that handles all the possible edge-cases. The logic required for a robust policy is anything but trivial and should incorporate an extensive testing.
****

== Out-of-the-box policies

=== FlexPolicy
This is the default policy that will be used if no other policy is specified when creating an instance of the `Roboquant` class. It provides several constructor parameters that influence its behavior.

[source, kotlin,indent=0]
----
include::{sourcefile}[tag=constructor]
----

You can also extend the FlexPolicy and overwrite some of its methods. For example, to create different order types you would implement something like this:

[source, kotlin,indent=0]
----
include::{sourcefile}[tag=default]
----

=== Chaining
There are several extension methods available that can add functionality to any type of policy by creating a chain of policies in which each policy has a particular tasks. Typically, the extension methods perform one of two tasks:

1. Remove signals before the next policy is invoked
2. Remove orders before they are handed to the broker

[source, kotlin,indent=0]
----
include::{sourcefile}[tag=chaining]
----


== Fractional Order sizes
Roboquant doesn't make assumptions on the minimal order and position sizes. They are not limited to integers only and so there is no restriction on using a broker that supports fractional trading. Since it is the Policy that create the orders, here you can also put any type of order size logic you require.

TIP: The `FlexPolicy` allows you to specify the number of decimals for sizing calculations, allowing to easily enable fractional orders.


== Custom Policies
In case the out-of-the-box policies will not do, you can implement your own `Policy`. You only have to implement a single method named `act`. This method has access to the generated signals and the `Account` and `Event` object.

[source, kotlin,indent=0]
----
include::{sourcefile}[tag=basic]
----

So a very naive and not robust implementation could look something like this:

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=naive]
----

Or using the more concise Kotlin way of doing things:
[source,kotlin,indent=0]
----
include::{sourcefile}[tag=naive2]
----


The following example is more realistic and shows an implementation that calculates the ATR (Average True Range). The ATR is then used to set the limit amount in a Limit Order. This example use the `FlexPolicy` as its base class that will take care of much of the logic like sizing and dealing with concurrent orders.
[source, kotlin,indent=0]
----
include::{sourcefile}[tag=custom3]
----

When developing custom policies, they should not only be robust and deal with corner-cases, but they should also be explainable. Back-testing over large amounts of data is already challenging enough without having a `Policy` in place whose behavior is very difficult to wrap your head around. So the KISS design principle (Keep It Simple, Stupid) applies to policies.

TIP: When creating an order in a Policy, always validate if you still have an open order for the same asset and take the appropriate action.


[#_advanced_policies]
== Advanced Policies
Most commonly, a `Policy` is used to transform signals it receives from the `Strategy` into orders. But there are use cases where the policy is not using Signals to create orders. Common use cases are:

. Re-balancing your portfolio at regular intervals (like monthly) based on some risk profile. Since a `Strategy` doesn't have access to an `Account` and therefore neither to a `Portfolio`, this needs to be done in a `Policy`.
. Advanced machine learning techniques like reinforcement learning that train the algorithm to directly create orders based on events (without creating intermediate signals).

In these cases you don't require a `Strategy` and you can implement all the logic in the `Policy` instead. You can use the `NoSignalStrategy` as strategy that doesn't perform any action.

The following example shows the boilerplate for a policy that at a regular interval (20 days) re-balances the portfolio:

[source, kotlin,indent=0]
----
include::{sourcefile}[tag=advanced]
----

