= Roboquant
:source-highlighter: rouge
:icons: font
:sourcefile: ../../samples/roboquant.kt
:jbake-date: 2020-10-01

== Create an Instance
The `Roboquant` class (org.roboquant.Roboquant) is the engine of the platform, not to be confused with _roboquant_ (all lower case) which is the name of the platform itself. An instance of the `Roboquant` class orchestrates the interaction between the components and performs the actual runs.

You are only required to provide a strategy when creating a new instance of _Roboquant_. So the bare minimum to get a working instance would look something like this:

[source, kotlin, indent=0]
----
include::{sourcefile}[tag=basic]
----

The following default values will be used if you don't provide additional parameters:

* No metrics will be captured at all
* The `SimBroker` will be used as the broker with its default settings
* The `FlexPolicy` will be the policy used
* The `MemoryLogger` for logging the metrics (although without any metrics to capture, there is not much to log)

Each of these defaults can be overwritten with a different implementation when you instantiate a `Roboquant`, as the following code snippet demonstrates:

[source, kotlin, indent=0]
----
include::{sourcefile}[tag=complete]
----

As you can see, you can provide multiple metrics, but only a single instance of the other components. But that doesn't mean you cannot use multiple strategies or policies. You can for example combine multiple strategies into one and pass that instance to the `Roboquant` constructor:

[source, kotlin, indent=0]
----
include::{sourcefile}[tag=combined]
----


== Run
After you have created an instance of the `Roboquant` class and have a xref:feed.adoc[data feed], you can start the run.

NOTE: The same `run` method is used for all the different stages, from back testing to live trading. See also xref:../background/four_stages.adoc[the 4 stages] for more details about these stages.

In the most basic form, you provide a feed as a single the argument to the `run` method. In that case, all the events available in the feed will be used in the run. So if your feed contains 100 stocks with each 20 years of end of day candlesticks, all that data will be used in a single run.

[source, kotlin, indent=0]
----
include::{sourcefile}[tag=run]
----

However, you can restrict a run to a certain timeframe. This is especially useful for live feeds, that would otherwise run forever. But it also comes in handy when using historic data, and you want to perform multiple runs over different times.

[source, kotlin, indent=0]
----
include::{sourcefile}[tag=run2]
----

You can invoke a run multiple times, for example with different timeframes. The following code shows how to use this to perform a walk-forward back test of two-year periods:

[source, kotlin, indent=0]
----
include::{sourcefile}[tag=run3]
----

== Running in Parallel
If you want to run many back-test, you can run them in parallel and leverage all the cores on your computer to expedite the process. _Roboquant_ scales almost linearly with the number of available cores, and it only requires a few extra lines of code.

The following example shows how to run a walk forward in parallel. By reusing the same logger instance, all results will be stored in a single instance and can be easily compared afterwards.

[source, kotlin, indent=0]
----
include::{sourcefile}[tag=runParallel]
----

