= roboquant website
:icons: font

This repo contains the content for the roboquant.org website. It uses JBake as the generator for the static website and asciidoc for most of the content. All the Kotlin code samples used in the documentation are in the samples directory and are compiled to make sure they
are correct and still up to date.

== Build
Not the JBake default output directory is used, but rather the ```docs``` directory. The reason for this is that the website is hosted on GitHub Pages and right now only / or /docs can serve as the content root and not other directories.

To generate the website, run:

[source,shell]
----
mvn jbake:generate
----

or if you have JBake installed, you can run:

[source,shell]
----
rm -rf docs
jbake . docs
----

NOTE: If you are on Apple Silicon (the M1 processor), the default JBake installation won't work. But there is a patch available that uses SQLLite under the hood and works. You can get it at: https://github.com/mhberger/jbake/tree/mhb/sqlite-2021-05-30[JBake SQLLite Patched]

To develop, you can run: 

[source,shell]
----
mvn jbake:inline
----

== Other
Check the roboquant site at https://roboquant.org[roboquant.org]

If you want to fork this for your own website, please be aware that the index.ftl template still has some hard coded content in there that you need to replace. The other pages use the content.