= Avro Feed
:icons: font
:source-highlighter: rouge
:sourcefile: ../../../samples/feed.kt
:jbake-date: 2020-01-09

Apache Avro™ is a data serialization system. Avro provides:

* Rich data structures.
* A compact, fast, binary data format.
* A container file, to store persistent data.

Avro files make it easy to store large amount of data in a single file and efficiently use it during back testing. The AvroFeed implementation of roboquant only loads data in memory when it is required, so very large datasets can be used without having to worry about memory issues.

Also since the Avro Feed uses a single file, it is easier to distribute than for example directories full of CSV files.

== Using an AvroFeed
To use any compatible Avro file as a feed is straight forward.You just provide the file location to the constructor as a parameter and the feed will be ready to use.

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=avro]
----

A single feed can contain mixed price actions if required.So you can have Trade Prices and Price Bars in the same feed.


[#_convert_to_an_avrofeed]
== Convert to an AvroFeed
You can also convert other feeds into Avro files that you can then later use for back-testing.This works with both historic data feeds as wel as live data feeds.The current limitation is that it only works with price actions and not other type of actions like image data or social media post.

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=avrocapture]
----

TIP: If you work a lot with directories full of CSV files, you can convert them to a single Avro file and use that from then on.This is both faster and has lower memory consumption.

The nice thing is that the recording also works with live feeds.So you can record a live feed for a specified timeframe and then use it from then on in your own back test.

The following example shows how you can record 4 hours of Bitcoin price-bars from Binance.

[source, kotlin, indent=0]
----
include::{sourcefile}[tag=avrocapturelive]
----



== Default AvroFeeds
Roboquant comes with a few default AvroFeeds. The main benefit is that you can quickly test if your code is working without having to download and set up your own feeds.

[source, kotlin, indent=0]
----
include::{sourcefile}[tag=predefined]
----

In the future there will be more default AvroFeeds that you can use, also depending on the feedback from the community. Likely candidates that are currently missing are FOREX feeds and cryptocurrency feeds.

WARNING: these default feeds should not be relied on for serious back testing.
