= Features
:jbake-type: doc
:icons: font
:source-highlighter: rouge
:sourcefile: ../../samples/features.kt
:jbake-date: 2020-06-01

== The 4 main objectives
Roboquant has 4 main objectives that determine most of its features: *<<Fast>>*, *<<Flexible>>*, *<<Friendly>>* and *<<Free>>*. All the features listed on this page can be directly linked to one of these 4 objectives.

== Fast
Nowadays, there is so much more data available than ever before. It would be a lost opportunity not being able to use this data to develop smarter and better performing strategies. Roboquant can work seamlessly with these large data-sets:

* [x] Use of multi-threading and coroutines to fully utilize modern hardware, like large multicore machines
* [x] Optimized and fine-tuned back-test engine so the engine itself will not become the bottleneck
* [x] Run multiple back-test in parallel
* [x] Very fast parallel CSV parsing, allowing to process directories full of CSV files in just seconds
* [x] Support for file formats like Apache Avro™ to further reduce parsing overhead and easily share data sets
* [x] Support for lazy loading of data, so memory doesn't become a constraint
* [x] Several very fast algorithms out of the box


== Flexible
Flexible means being able to trade at different markets at different parts in the world. This implies:

* [x] Support for trading assets in different currencies at the same time
* [x] Roboquant comes out of the box with ready to use currency converters
* [x] Correctly handles data from different time-zones
* [x] Trade traditional asset classes like stocks, options, futures and forex as well as cryptocurrencies
* [x] Support for simple trading strategies and advanced machine learning based approaches
* [x] Support for simple and advanced order types

Flexible also means _roboquant_ is fully modular and can be extended:

* [x] Integrate with 3rd party brokers and exchanges
* [x] Add new type of data feeds ranging from price feeds and fundamental data to unstructured data like images
* [x] Support for custom order types

== Friendly
Developing trading algorithms requires a lot of different skills. You need to know of course a lot about trading itself, but also programming and even a bit of statistics comes in handy. Roboquant tries to cater for both experienced and less experienced users and make it as user-friendly as possible without sacrificing the other objectives.

=== Trading specific Domain Model
Rather than having a generic framework where you still have to code a lot to make it usable, _roboquant_ approach is that of a trading specific domain model. For example, you can easily work with monetary amounts:

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=friendly1]
----

=== Interactive Development
Roboquant can be run inside a Jupyter Notebook which makes it easy to explore and experiment different ideas. Any code you developed in the notebook, you can at a later stage be used in a standalone application if you want to move to live trading.

A lot of effort went into designing an API that is easy to use from a Notebook and add features that make sense in the context of algo-trading:

* [x] Many charts out of the box that provides insights into the feeds and the results of a run
* [x] Graceful introduction of complexity.In other words: simple things should be simple, complex things should be possible
* [x] Many convenience methods to get results with minimal amount of coding
* [x] Sensible defaults for many arguments, so you don't have to specify them all the time

Another example, if you want to plot a chart, you don't first have to mangle data to make it consumable by the chart. In _roboquant_ the charts understand the key domain concepts like Account, Trades and Metrics and can plot these directly.

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=friendly2]
----

Once you code base grows too large for a notebook, the same code can be used in a traditional IDE.

[#_order_management]
=== Order Management
One of the hardest (and most overlooked) aspect of algorithmic trading is order management, especially when your goal is to come to a robust live trading environment. There are many things that potentially can go wrong and will cost you real money. It is a real endeavor to translate signals into actual orders and manage these outstanding orders.

Because of this, _roboquant_ separates the generation of signals (Strategy) from the actual orders (Policy). This allows algo-traders to focus on the generation of signals and pick the order management that fits their risk profile and trading style. And if full control over portfolio- and order-management is required, it is still available.

=== Batteries included
* [x] Over 150 technical indicators that are easy to use in your own strategies
* [x] Powerful charts when running back-tests in a Jupyter Notebook
* [x] Support for many back-testing approaches, like for walk-forwards and random samples
* [x] Pluggable metrics you can use to see how a strategy is performing
* [x] An advanced simulated broker for back-testing and live-testing that can handle both basic and advanced order types
* [x] Integration with 3rd party brokers and data providers

== Free
In order to build the best platform for algo-trading possible, we think it is important to make sure this platform is free for anyone to use, contribute and improve upon. That is why _roboquant_ is developed under the permissive Apache 2.0 license and welcomes people to contribute.

But it doesn't stop at the software. For real progress also data has to become freely available so performance of various strategies can be more easily compared. This is still very much work in progress, but for sure on the agenda of _roboquant_.

.Deep Learning Datasets
****
For inspiration, look at what quality training data did for progress of AI in recent years. By having standardized sets of data that are known to be of good quality and representative, it became much easier to compare different network architectures and continue to improve those that showed the best performance.

The same can hopefully also be achieved in the algo-trading world, so we can easily compare strategies and reproduce results.
****

== Feature Comparison
The following table provide a short overview of how the features of _roboquant_ stack up to some alternative algo-trading frameworks.

Of course, we are not completely objective, so we recommend trying them out for yourself and see which one suits you best.

[frame=ends]
[.table]
[cols="<,^,^,^,^"]
|===
|Feature |roboquant |Backtrader | Zipline| Lean (QuantConnect)

|Back Testing|&check;| &check;| &check;| &check;
|Live Testing|&check;| &check;| | &check;
|Paper Trading|&check;| &check;| | &check;
|Live Trading| &check;| &check;| | &check;
|Primary Language| Kotlin| Python| Python| C#
|License| Apache| GPL| Apache| Apache
|Active Development|&check;| | | &check;
|Multi Currency| &check;| | |
|Crypto Exchanges| &check;| &check;| | &check;
|Advanced Order Types| &check;| &check;| | 
|Multi Region| &check;| | |&check;
|Performance| high| low| low| mid
|Code base| small| midsize| large| very large
|Jupyter Notebook| &check;| &check;| &check;|
|Completely Free| &check;| &check;| |
|===
