= Features
:jbake-type: doc
:icons: font
:jbake-date: 2020-06-01

Roboquant has 4 main objectives that determine most features: Fast, Flexible, Friendly and Free.

== Fast
Nowadays, there is so much more data available than ever before. It would be a lost opportunity not being able to use this data to develop smarter and better performing strategies. Roboquant can work seamlessly with these large data-sets:

* [x] Fully utilize modern hardware, like large multicore machines
* [x] Optimized back-test engine so the engine itself will not become the bottleneck
* [x] Run multiple back-test in parallel
* [x] Very fast CSV parsing, allowing to process directories full of CSV files in just seconds
* [x] Support for file formats like Apache Avro™ to further reduce parsing overhead and easily share data sets
* [x] Support for lazy loading of data, so memory doesn't become a constraint
* [x] Several very fast algorithms out of the box


== Flexible
Flexible means being able to trade at different markets at different parts in the world. This implies:

* [x] Support for trading assets in different currencies at the same time.
* [x] Roboquant comes out of the box with ready to use currency converters
* [x] Correctly handles data from different time-zones
* [x] Trade traditional asset classes like stocks, options, futures and forex as well as cryptocurrencies
* [x] Support for simple trading strategies and advanced machine learning based approaches
* [x] Support for simple and complex order types

Flexible also means roboquant is fully modular and can be extended:

* [x] Integrate with 3rd party brokers and exchanges
* [x] Add new type of data feeds ranging from price feeds and fundamental data to unstructured data like images
* [x] Support for custom order types

== Friendly
Developing trading algorithms requires a lot of different skills. You need to know of course a lot about trading itself, but also programming and even a bit of statistics comes in handy. Roboquant tries to cater for both experienced and less experienced users and make it as user-friendly as possible without sacrificing the other objectives.

=== Trading specific Domain Model
Rather than having a generic framework where you still have to code a lot to make it usable, roboquant approach is that of a trading specific model. For example, if you want to plot a chart, you don't first have to mangle data to make it consumable by the chart. In roboquant the charts understand the key domain concepts like Account, Trades and Metrics and can plot these directly.

=== Interactive Development
Roboquant can be run inside a Jupyter Notebook which provides a very easy entry for people who might find a full-blown development environment too much hassle.A lot of effort went into designing an API that is very easy to use from a
Notebook.

* [x] Graceful introduction of complexity.In other words: simple things should be simple, complex things should be possible
* [x] Many convenience methods to get results with minimal amount of coding
* [x] Many charts out of the box that provides insights into the feeds and the results of a run
* [x] Sensible defaults for many arguments, so you don't have to specify them all the time

Once you code base grow too large for a notebook, the exact same code can be used in a traditional IDE.

[#_order_management]
=== Order Management
One of the hardest (and most overlooked aspect) of algorithmic trading is order management, especially when your goal is to bring it to a live trading environment.There are so many things that potentially can go wrong and will cost you real money.It is a real endeavor to translate signals into actual orders and manage these outstanding orders.

Because of this, roboquant separates the generation of signals (Strategy) from the actual orders (Policy).This allows algo-traders to focus on the generation of signals and pick the order management that fits the risk profile and trading style.And if full control over portfolio- and order-management is required, it is still available.

=== Batteries included
* [x] Over 150 technical indicators that are easy to use in your own strategies
* [x] Powerful charts when running back-tests in a Jupyter Notebook
* [x] Support for many back-testing approaches, like for walk-forwards and random samples
* [x] Pluggable metrics you can use to see how a strategy is performing
* [x] An advanced simulated broker for back-testing and live-testing that can handle both basic and advanced order types
* [x] Integration with 3rd party brokers and data providers

== Free
In order to build the best environment for algo-trading possible, it is important to make sure this environment is free for anyone to use, contribute and improve on. That is why roboquant is developed under the permissive Apache 2.0 license and welcomes people to contribute.

But it doesn't stop at the software. For real progress also data has to become freely available so performance of various strategies can be more easily compared.

.Deep Learning
****
For inspiration look at what quality training data did for deep learning networks and the progress in recent years. By having a standardized sets of data that are known to be of good quality and representative, it became much easier to compare different network architectures and continue to improve those that shows promise.

The same hopefully can also be achieved in the algo-trading world, so we can easily validate claims.
****

== Feature Comparison
The following table provide a short overview of how the features of roboquant stack up to some alternative algo-trading frameworks. Of course, we are not completely objective, so we recommend trying them out yourself and see which one suits you best.

[frame=ends]
[.table]
[cols="<,^,^,^,^"]
|===
|Feature |roboquant |Backtrader | Zipline| Lean (QuantConnect)

|Back Testing|&check;| &check;|  &check;| &check;
|Live Testing|&check;| &check;|  &cross;| &check;
|Paper Trading|&check;| &check;| &cross;| &check;
|Live Trading| &check;| &check;| &cross;| &check;
|Primary Language| Kotlin| Python| Python| C#
|License| Apache| GPL| Apache| Apache
|Active Development|&check;| &check;| &cross;| &check;
|Multi Currency| &check;|  &cross;| &cross;| &cross;
|Crypto Exchanges| &check;|  &check;| &cross;| &check;
|Advanced Order Types| &check;| &check;| &cross;| &cross;
|Multi Region| &check;|  &cross;| &cross;|&check;
|Performance| high| low| mid| high
|Code base| small| midsize| large| very large
|Jupyter Notebook| &check;|  &check;| &check;| &cross;
|Completely Free| &check;|  &check;| &cross;| &cross;
|===


.