= Community
:jbake-type: page
:jbake-status: published
:jbake-heading: testing leads to failure, and failure leads to understanding
:icons: font

There are several ways to get into contact, ask questions, contribute, and share your experience regarding roboquant.

== icon:github[1x] GitHub
If you find a bug or know of a great feature to add to roboquant, best to raise an issue in GitHub. Issues are used to track todos, bugs, feature requests, and more.As issues are created, they’ll appear here in a searchable and filterable list. Before you create a new issue, please check if not someone else already raised a similar ticket.To see the open issues and create a new one, click over https://github.com/neurallayer/roboquant/issues[here]

TIP: if you want to contribute, this is a great place to check what still needs to be done and ask for advice what to work on.

== icon:reddit[1x] Reddit
For more general chat and questions about roboquant and trading strategies, there is a reddit channel.Since documentation is still lacking, this is a good to find out more. Join the https://www.reddit.com/r/roboquant/[r/roboquant] subreddit.

== icon:slack[1x] Slack
If you want to contribute to the code base, Slack is where most development related discussions are happening. Join the https://roboquant.slack.com[roboquant] Slack workspace.

== icon:twitter[1x] Twitter
Follow roboquant news on Twitter to stay up to date on updates and new versions of the software: https://twitter.com/roboquant_news[@roboquant_news]. There will be an automatic tweet generated whenever there a push of new functionality to the source repository.
