= Community
:jbake-type: page
:jbake-status: published
:jbake-heading: testing leads to failure, and failure leads to understanding
:icons: font

There are several ways to get into contact, ask questions, contribute, and share your experience regarding roboquant.

== icon:users[1x] Discord
Roboquant has its own Discord server with various channels to discuss algo-trading in general and to get help on developing your own strategies using the roboquant platform.

Since the roboquant documentation is still lacking in certain areas, this is a great place to ask questions and find out more about the platform.

Invite link: https://discord.gg/Vt9wgNjSzw[join roboquant]


== icon:github[1x] GitHub
If you find a bug or know of a great feature to add to roboquant, best to raise an issue on GitHub. Issues are used to track todos, bugs, feature requests, and more. As issues are created, they’ll appear there in a searchable and filterable list. Before you create a new issue, please check if not someone else already raised a similar ticket. To see the open issues or create a new one, head over to https://github.com/neurallayer/roboquant/issues[here]

TIP: if you want to contribute, this is a great place to check what still needs to be done and ask for advice what to work on.


== icon:envelope[1x] Email
Although we encourage that questions and remarks are shared in the broader community so everyone can learn from it, you can also drop us an email at mailto:info@roboquant.org[]
