= Documentation
:jbake-type: page
:jbake-status: published
:jbake-heading: testing leads to failure, and failure leads to understanding
:icons: font


== Tutorial
A comprehensive xref:tutorial/index.adoc[tutorial], well suited if you are new to _roboquant_ or just want to understand the core concepts. It comes with many code samples to get you started and explains how to develop your own strategies.

== How-to
A series of how-to notebooks focus on achieving a particular task, like how to integrate with Binance or how to use technical indicators in your strategy. You can run the notebooks on your local machine or use a free online environment like MyBinder.org to run them.

To find out more, go to https://github.com/neurallayer/roboquant-notebook/tree/main[GitHub], or if you just want to try it without any installation, click image:https://mybinder.org/badge_logo.svg[Binder,link=https://mybinder.org/v2/gh/neurallayer/roboquant-notebook/main?urlpath=tree/notebooks/, window=_blank]

== Background info
Click xref:background/index.adoc[here] to find out why _roboquant_ was created in the first place and some key features and benefits. It will also provide an overview of the xref:background/four_stages.adoc[4-stage] process of developing robust trading strategies.

== Reference
The _roboquant_ source code documentation (work-in-progress).

== Community Help
See the xref:community.adoc[Community page] on how to get help if you couldn't find the information in the documentation.


