= Documentation
:jbake-type: page
:jbake-status: published
:jbake-heading: testing leads to failure, and failure leads to understanding
:icons: font

== Introduction
There are several ways to learn more about _roboquant_. We use the documentation approach as first introduced by Divio and now adopted by many projects to split the documentation in different sections:

If you are interested, you can find out more at https://documentation.divio.com/introduction/#making-documentation-work[Divio]

== Tutorial
A comprehensive xref:tutorial/index.adoc[tutorial], well suited if you are new to roboquant. It comes with many code samples to get you started.

== Background
Click xref:background/index.adoc[here] to find out why _roboquant_ was created in the first place and some key features and benefits. It will also provide an overview of the xref:background/four_stages.adoc[4 stages] process of developing robust trading strategies.

== How-to Notebooks
These notebooks focus on achieving a particular task, like how to integrate with Binance or how to use technical indicators.
You can run the notebooks on your local machine or use an online notebook provider like MyBinder.org to run them.

To find out more, go to https://github.com/neurallayer/roboquant-notebook/tree/main[GitHub]. Or if you just want to try it without any installation, go to image:https://mybinder.org/badge_logo.svg[Binder,link=https://mybinder.org/v2/gh/neurallayer/roboquant-notebook/main?urlpath=lab/tree/tutorials]

== API reference
The _roboquant_ code API (work in progress).

== Community Help
Head over to the _roboquant_ Discord Server if you have questions. If you have not yet joined: https://discord.gg/Vt9wgNjSzw[join roboquant, window=_target]


