= Four Stages
:jbake-type: doc
:jbake-status: published
:jbake-heading: testing leads to failure,<br> and failure leads to understanding


== Four Stages
There are 4 distinct stages that you go through when you develop and run of a new trading strategy. Each stage has its own purpose and benefits. If possible at all, it is best not to skip a stage. And perhaps more important, if you are not happy about the performance in a later stage, go back to the first stage.

[plantuml, "four_stages", "svg"]
----
@startuml
!theme spacelab
rectangle "Back Testing" as BT
rectangle "Live Testing" as LT
rectangle "Paper Trading" as PTR
rectangle "Live Trading" as LTR

BT -> LT
LT -> PTR
PTR -> LTR
@enduml
----

Roboquant support all four stages and requires minimal changes to your code to move from one stage to the next. Your strategy and policy should not change at all, and only the selected data feed and broker may differ between stages.

== Stage 1: Back Testing
In this stage you'll use historic data and the ```SimBroker``` that comes with roboquant to test your strategy and policy. 

You can of course run a single back test over the complete timeline of historic data. But roboquant makes it easy to also run walk forward and randomly sampled time-frames that will give you more insights into the performance under different regimes. It is very important to get as many insights as possible about the overall performance and behavior, so you know what to expect and also what not expect when you finally will go live.

This is also the only stage where you should develop and modify your strategy and policy. If you are not happy with the performance at a later stage, you should return this first stage and make the changes here. If for example you would like to use circuit-breakers during live trading to give some extra peace of mind, you should already include this logic during back testing.

== Stage 2: Live Testing
In this stage you'll use live data and the ```SimBroker``` to test your strategy and policy. The main purpose is to validate if your strategy is still performing well on real unseen data.

It is very easy to over fit your strategy during back testing, and this stage provides some confirmation if that is the case. That being said, often you cannot run this stage for as long as required to have a perfect insight into over fitting, so this is an indication at best.

== Stage 3: Paper Trading
In this stage you'll use live data with a paper trading account to test your strategy and policy. Of course this will only work if your broker offers paper trading. But if you are serious about algo-trading, you should only select a broker that offers a realistic paper trading account.

The main purpose is to validate if your policy is still performing well using a different broker implementation. For example, are the order types generated by the policy fully supported and behave as expected.

This stage is where you really validate the robustness of your approach and give extra confirmation that it is ready to go live. If you don't have a solid policy in place that fully behaves as expected, you should never go to the next stage.

== Stage 4: Live Trading
In this stage you'll use live data and the live trading account to run your strategy and policy and now real money is at stake. And although not any more testing, you will need to closely monitor the performance and take appropriate actions. One reason is that even paper trading is a simulation and cannot fully prepare for live trading.

== First draft

[plantuml, "main_flow", "svg"]
----
@startuml
!theme spacelab
rectangle Feed
rectangle Strategy
rectangle Policy
rectangle Broker
rectangle Metric
rectangle MetricsLogger

Feed -> Strategy
Strategy -> Policy
Policy -> Broker
Broker -> Metric
Metric -> MetricsLogger
@enduml
----