= Buying Power
:source-highlighter: rouge
:sourcefile: ../../../samples/feed.kt
:jbake-date: 2020-01-31

Buying power allows modelling different types of accounts, like a Cash Account or Margin Account when using the SimBroker. It represents the amount available for trading,

Out of the box roboquant comes with several models that cather for common account types:

1. Cash accounts, that don't have leverage or margin
2. Margin account, that have configurable margin and leverage


== Cash Accounts
Cash accounts can be modelled using the `CashBuyingPowerModel`. This model is also the default if you don't provide a BuyingPowerModel when instantiating a xref:simbroker.adoc[SimBroker].

`CashBuyingPowerModel` only basis the buying power on the available cash, and no margin is calculated and no leverage is used..

The below table shows an example using the default CashBuyingPowerModel when trading in different currencies, EUR and USD in this case.

[%autowidth, cols="^,<,>,>,>,>,>,>,>"]
|===
|Time |Action |Cash |Portfolio |Margin |Equity |Buying Power |Unrealized PnL |Realized PnL

|1 |open account with €10,000|€10,000|0|0|€10,000|€10,000|0|0
|2 |buy ABC 40 @ €100|€6,000|€4,000|0|€10,000|€6,000|0|0
|3 |price ABC drops to €75|€6,000|€3,000|0|€9,000|€6,000| -€1,000|0
|4 |sell ABC -40 @ €75|€ 9,000|0|0|€ 9,000|€9,000|0| -€1,000
|5 |buy XYZ 25 @ $200|€9,000 -$5,000|$5,000|0|€9,000|€4,500|0| -€1,000
|6 |price XYZ raises to $240|€9,000 -$5,000|$6,000|0|€9,000 $1,000|€4,500|$1,000| -€1,000
|7 |sell XYZ -25 @ $240|€9,000 $1,000|0|0|€9,000 $1,000|€9,900|0| -€1,000 $1,000
|===


== Margin Accounts
Margin based accounts can be modelled using the `MarginBuyingPowerModel`. This model supports:

1. Initial margin (aka leverage)
2. Maintenance margin, with support for different values for long and short positions
3. Minimum amount of required equity that cannot be used as margin

All margin calculations are based on the equity of the account, and not only the cash. And although in the below tables the (maintenance) margin is shown, it is actually not exposed. Only the Buying Power value is available through the account object.

The logic of calculating the buying power looks roughly like this (excluding open orders):

      long value = long positions * maintance margin long
      short value = short positions * maintance margin short
      excess margin = equity - long value - short value - minimum equity
      buying power = excess margin * ( 1 / initial margin)

The following table shows an example for long trading with margin account in a Japanese Yen, using the following (default) values:

- initial margin: 50%
- maintenance margin: 30% (both for long and short positions)
- no minimum equity is required

Also, there are no commissions or other cost associated with the transactions. This is not a recommended approach, but just used here to make it a bit simpler to comprehend.

[%autowidth, cols="^,<,>,>,>,>,>,>,>"]
|===
|Time |Action |Cash |Portfolio |Margin |Equity |Buying Power |Unrealized PnL |Realized PnL

|1 |open account with ¥1,000,000|¥1,000,000|0|0|¥1,000,000|¥2,000,000|0|0
|2 |buy ABC 500 @ ¥1,000|¥500,000|¥500,000|¥150,000|¥1,000,000|¥1,700,000|0|0
|3 |ABC drops to ¥500|¥500,000|¥250,000|¥75,000|¥750,000|¥1,350,000|-¥250,000|0
|4 |buy ABC 2000 @ ¥500|-¥500,000|¥1,250,000|¥375,000|¥750,000|¥750,000|-¥250,000|0
|5 |ABC drops to ¥400|-¥500,000|¥1,000,000|¥300,000|¥500,000|¥400,000|-¥500,000|0
|6 |sell ABC -2500 @ ¥400|¥500,000|0|0|¥500,000|¥1,000,000|0|-¥500,000
|===

The following table shows another example, but this time shorting on a USD margin account. It uses the same default values for the margin calculations as the above table.

[%autowidth, cols="^,<,>,>,>,>,>,>,>"]
|===
|Time |Action |Cash |Portfolio |Margin |Equity |Buying Power |Unrealized PnL |Realized PnL

|1 |open account with $20,000|$20,000|0|0|$20,000|$40,000|0|0
|2 |sell XYZ -50 @ $200|$30,000|-$10,000|$3,000|$20,000|$34,000|0|0
|3 |price XYZ raises to $300|$30,000|-$15,000|$4,500|$15,000|$21,000|-$5,000|0
|5 |sell XYZ -50 @ $300|$45,000|-$30,000|$9,000|$15,000|$12,000|-$5,000|0
|6 |buy XYZ 100 @ $300|$15,000|0|0|$15,000|$30,000|0|-$5,000
|===


== Orders

The following rules apply when taken into account open orders when calculating the buying power:

- until an order is accepted, it doesn't impact margin or buying power.
- open orders that reduce a position, don’t require buying power. So you can always close a position, both short and long positions.
- Once an order has been accepted and is in an open state, it will not be cancelled due to lack of buying power.
- An order is closed state will not impact margin or buying power (so similar to INITIAL state)

