= Broker
:source-highlighter: rouge
:sourcefile: ../../../samples/feed.kt
:jbake-date: 2020-12-20
:icons: font

Broker is an interface that has two types of implementations:

1. The SimBroker, which is a simulation of a real brokers and can be used during back-test and live-test.
2. Integrations with real brokers/exchanges, using their paper-trading and live-trading platforms to do the actual order execution. In this case the `Broker` implementation in roboquant is just a proxy.

This section of the documentation covers the SimBroker. But if you want to know about integration with real brokers, check out the section about integration.


== Broker Interface
The Broker interface itself is surprisingly simple. It contains one property and one method (next to the default Component interface methods)

- the property is `account`, which hold all the exposed state, like portfolio and orders.
- the method is `place(orders: List<Order>, event: Event)` which enables you to place orders at this broker.

Normally you don't invoke the `place` method directly, but use `roboquant.run` method to run a trading strategy and it
will call the `place` method as part of its flow.

== Account
The `Account` object contains all the exposed state of a broker and is identical between the simulated broker and real brokers.

It contains the following key attributes:

- base currency to use
- cash balance
- portfolio with all the (open) positions
- trades that contain all the trade executions that happened so far
- orders, both active orders and closed orders
- amount of buying power available for trading

TIP: Use the `buyingPower` property if you want to know how much cash is remaining for trading. Using the `cash` balance might not always return the value you expect and might even differ between broker implementations.





