= Simulated Broker
:source-highlighter: rouge
:sourcefile: ../../../samples/feed.kt
:jbake-date: 2020-03-21

You use the `SimBroker` class (short for Simulated Broker) both for the back testing and live testing stages. See also the xref:../introduction/four_stages.adoc[four stages] for more info about the different stages when developing trading strategies.

SimBroker can simulate a wide range of brokers and the exchanges. Besides several configuration options that are available,  the behavior can be further extended by providing custom models for cost and buying power calculations.


== Order Handling
When an order is placed at the SimBroker, it only gets processed once there is a known price for the underlying asset. Till an event happens that has that price available, the order will remain in its INITIAL state.

Any TIF (Time In Force) enforcement of order execution will only start after an order has been accepted (so it is in open state). So an order in INITIAL state cannot expire and time based TIF only start counting after it has been accepted.

Any open orders will be processed based on FIFO, so older open orders are processed first. Exception to this rule are cancellation orders that are always processed before other order types.

== Initial Deposit
The initial deposit is the cash that is deposited at the opening of an account. Any time the SimBroker is reset, the account will be reset to this initial deposit.

Typically, the initial deposit is denoted in a single currency, like a `$50,000.00 USD` account. But this is not a hard requirement and in roboquant™ you can use multi-currency initial deposit if you like.


== Custom Models
Custom models are a way to further customize the behavior of `SimBroker`. The following two types of models can implemented if the default ones that comes with roboquant are not sufficient.

- Cost models: the transaction related cost like slippage and fees/commissions. It is important to notice that if you don't take these type of cost into account, your profitable strategy in back-test might turn out not to be that profitable in live trading.

- Buying power models: the different type of funding of an account, like a Cash or Margin account. See the page about xref:buyingpower.adoc[buying power] for more details.

== Limitations

Like any simulation, SimBroker also has limitations compared to a real life trading. It is important to realize this and take appropriate actions where possible:

1. The default cost calculations become less realistic if you trade large amount compared to overall daily volume. Don't underestimate the transaction cost like spread, slippage and commissions and rather be too pessimistic.
2. Order types might behave slightly different between SimBroker and different real brokers. If possible at all, also perform paper trading to see if your solution still performs as expected.
3. The buying power and margin calculations might differ. Be on the safe side and use a higher margin requirement in the SimBroker than required.


