= Overview
:jbake-date: 2020-01-31

There are three types of integrations available within roboquant with external parties:

. Historic data providers
. Live data providers
. Brokers

In some cases a single 3rd party provides all three types of integration (like Interactive Brokers or Alpaca), or sometimes they are just specialised for a subset (like IEX Cloud that only provides historic and live data).

You can combine several of these 3rd parties together, for example the data feeds from IEX Cloud and the broker
functionality from Alpaca.


== Modules & Packages
The third party integrations have their own modules:

* roboquant-extra for all "traditional" trading
* roboquant-crypto for all cryptocurrency related 3rd parties

Include these in your Maven or Gradle build. They are by default already included in the Jupyter Notebooks.

In order to use the 3rd party integration, you'll first have to import the package. All third party integration have their own package directly under org.roboquant

So you can import all the classes for OANDA as follows:

[source, kotlin]
----
import org.roboquant.oanda.*
----


== Configuration
When you want to integrate a 3rd party, you most likely require credentials to gain access. Often this is in the form of an  API id and key. Although you can embed these directly in your source code, roboquant supports better and more secure alternatives.

The following shows the steps how roboquant resolves these configuration parameters:

. If the credentials are provided directly in the software when calling the API use these, otherwise go to next step.
. If the credentials are provided as startup parameter to the JVM with the -D syntax use these, otherwise go to next step.
. If the credentials are set as system environment use these, otherwise go to next step.
. If the credentials are set in a property file called ".env" in the working directory use these, otherwise go to next step.
. If the credentials are set in a property file called "dotenv" in the working directory use these, otherwise go to next step.
. If the credentials are set in a property file called ".env" in the $HOME/.roboquant directory use these, otherwise go to next step.


== Supported 3rd parties
The following 3rd parties are supported:

|===
|3rd party |historic feed |live feed |broker

|xref:ibkr.adoc[Interactive Brokers]|Y|Y|Y
|xref:alpaca.adoc[Alpaca]|Y|Y|Y
|xref:oanda.adoc[OANDA]|Y|Y|Y
|xref:iex.adoc[IEX Cloud]|Y|Y|N
|xref:yahoo.adoc[Yahoo Finance]|Y|N|N
|xref:alphavantage.adoc[Alpha Vantage]|Y|N|N
|===


Roboquant also supports many crypto exchanges. For more details on that, see the xref:crypto.adoc[crypto] documentation.

NOTE: roboquant is open source software that is developed independently of these 3rd party providers.
