= Signal
:source-highlighter: rouge
:icons: font

A signal is the outcome of a strategy and is modelled closely after the ratings given by ratings agencies. The two mandatory parts of a signal are:

1. The asset that the signal applies for
2. A rating for that same asset

There is a 5-point scale used for the rating part of a signal:

* Buy: Also known as strong buy and "on the recommended list". Buy is a recommendation to purchase a specific security.
* Sell: Also known as strong sell, it's a recommendation to sell a security or to liquidate an asset.
* Hold: In general terms, a company with a hold recommendation is expected to perform at the same pace as comparable companies or in-line with the market.
* Underperform: A recommendation that means a stock is expected to do slightly worse than the overall stock market return. Underperform can also be expressed as "moderate sell," "weak hold" and "underweight."
* Outperform: Also known as "moderate buy," "accumulate" and "overweight." Outperform is an analyst recommendation meaning a stock is expected to do slightly better than the market return.

NOTE: a hold rating  is not the same as no signal. Only generate hold signals if you think the asset will perform market conform.

[source, kotlin]
----
    // apple is of the type Asset
    val signal = Signal(apple, Rating.BUY)
----