= Metrics Logger
:icons: font
:source-highlighter: rouge
:sourcefile: ../../../samples/logger.kt
:jbake-date: 2020-01-15

A `MetricsLogger` receives the calculated metric values at the end of each step and then stores and/or logs these values.


== Standard Loggers

=== MemoryLogger
This is the default logger used if no other logger is configured. It stores all the recorded values in memory and
allows them to be queried afterwards. It also comes with a progress-bar that shows how much time is remaining during
a run.

This logger is very useful if you are testing your approach in a Jupyter Notebook or another interactive development
environment.

[source,kotlin,indent=0]
----
include::{sourcefile}[tag=standard]
----


=== SilentLogger
This logger just silently ignores all metrics and is mostly useful for unit tests

=== InfoLogger
Logs metrics using the built-in Logger.

=== ConsoleLogger
Logs the metrics to the console using a simple "println" statement.

== Custom Loggers
You can implement also your own MetricsLogger, for example if you want to store values into a database or have a custom file format that you want to use.

[source,kotlin,indent=0]
----
----